name: MLflow CI Training

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Conda & Run MLflow Project
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: personality-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow and Run Project
        shell: bash -l {0}
        run: |
          pip install mlflow
          mlflow run MLProject

      - name: Upload classification report
        uses: actions/upload-artifact@v4
        with:
          name: classification_report
          path: MLProject/classification_report.txt
