name: MLflow CI Training

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Conda & Run MLflow Project
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: personality-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow and Run Project
        shell: bash -l {0}  # ⬅️ ini penting untuk pakai shell Conda
        run: |
          pip install mlflow
          mlflow run MLProject
